### ISSUE TITLE
Do I need to disconnect the remote completely in order to use it?

### ISSUE THREAD

**Issue by Madelena** [robert-friedland/ha-bedjet#1]
The tips in Readme mentioned that a Bedjet can only connect to one bluetooth device at a time. Does that mean I need to disconnect and remove the bedjet from my remote first? I'm not sure how to pair the Bedjet to the HA Raspberry Pi.

Thank you for making this integration!

**Comment by robert-friedland** [comment]
No, you don't need to disconnect it -- in fact, it seemed like it was one connection at a time while I was trying to get the integration to work, but lately I've had both the integration and the remote working fine simultaneously. I'll update that section of the readme.

To pair the Bedjet to the HA Raspberry Pi, you need to find the Bedjet's Bluetooth MAC address using something like [Bluetooth LE Explorer](https://apps.microsoft.com/store/detail/bluetooth-le-explorer/9N0ZTKF1QD98?hl=en-us&gl=US). The Bedjet will be the device named BEDJET_V3.

Once you have the MAC address, you just need to reference it in your config.yaml as a climate entity.

```climate:
  - platform: ha_bedjet
    name: BedJet
    mac: '54:98:23:62:3e:0f

**Comment by tomgidden** [comment]
I can confirm, it works fine for me with the remote and HA running concurrently -- change in HA, the remote immediately updates.  

The iOS app, however, does seem to be failing to connect to it now.  Does the remote use the same protocol/transport as the app and/or HA?  If not, maybe the remote will work concurrently with HA _or_ the iOS app, but not both...?

Incidentally, I found my BLE MAC address on the Pi using:
```
sudo hcitool lescan --discovery=g
```

If it helps, my brand-new 220V (UK) BEDJET_V3 reported with a MAC address starting `E0:E2:E6:…` which I believe is an Espressif range, eg. ESP32.

Thanks for your fine work @robert-friedland; I was dreading having to write my own integration and/or Node-RED hack job as per usual!

**Comment by Madelena** [comment]
Hmmm I'm still at a loss.

I found my BedJet using Bluetooth LE Explorer:

<img width="901" alt="ha_bedjet Bug - Bluetooth LE Explorer" src="https://user-images.githubusercontent.com/4341881/173164160-857f719b-dbdf-400e-8a8c-607327419048.png">

So I add this in my `configuration.yaml`:

```yaml
climate:
  - platform: ha_bedjet
    name: BedJet
    mac: 'CC:50:E3:A0:AC:5A'
```

And the Raspberry Pi with my Home Assistant can detect the device just fine:

<img width="960" alt="ha_bedjet Bug - Terminal" src="https://user-images.githubusercontent.com/4341881/173164207-c253c73a-7b32-460e-9962-a3dc7da578e6.png">

Yet I still get an error:

```log
2022-06-10 06:00:31 ERROR (MainThread) [homeassistant.components.climate] Error while setting up ha_bedjet platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_bedjet/climate.py", line 68, in setup_platform
    [BedJet(name, mac, ADAPTER)]
  File "/config/custom_components/ha_bedjet/climate.py", line 110, in __init__
    raise Exception(f'Could not establish connection to {self._name}.')
Exception: Could not establish connection to BedJet.
```

**Comment by robert-friedland** [comment]
@Madelena can you try:
1. Remove the batteries from the BedJet remote (to make sure it's off and not interfering)
2. Restart Home Assistant

Hopefully that'll do the trick, and then you can pop the batteries back into the remote... if not, I'm not sure what the issue could be :/
